import { useNavigate } from "react-router-dom";
import Navbar from "../../components/layout/Navbar";
import Footer from "../../components/layout/Footer";
import { guestLogin } from "../../services/authService";
import "./Landing.css";

export default function Landing() {
  const navigate = useNavigate();
  return (
    <>
      <Navbar />

      <section className="hero">

        <div className="hero-content">

          <h1>
            Watch.
            <br />
            Listen.
            <br />
            Learn.
          </h1>

          <p>
            Transform YouTube videos into AI-powered podcasts.
            Switch between video and audio instantly and continue learning anywhere.
          </p>

          <div className="hero-buttons">
            <button className="primary-btn" onClick={() => navigate('/dashboard')}>
              Get Started
            </button>

            <button className="secondary-btn" onClick={async () => {
              try {
                const res = await guestLogin();
                if (res.data.success) {
                  sessionStorage.setItem("token", res.data.token);
                  sessionStorage.setItem("user", JSON.stringify(res.data.user));
                  navigate('/dashboard');
                }
              } catch (err) {
                console.error("Guest login failed", err);
                navigate('/dashboard');
              }
            }}>
              Explore
            </button>
          </div>

        </div>

      </section>

      <section id="features" className="section-container features">
        <h2>Features</h2>
        <div className="grid">
          <div className="card">
            <h3>AI Transcripts</h3>
            <p>Automatically transcribe your audio and video with high accuracy.</p>
          </div>
          <div className="card">
            <h3>Smart Summaries</h3>
            <p>Get concise summaries and chapter breakdowns generated by Gemini AI.</p>
          </div>
          <div className="card">
            <h3>Seamless Translation</h3>
            <p>Expand your audience by translating your content into multiple languages.</p>
          </div>
        </div>
      </section>

      <section id="how-it-works" className="section-container how-it-works">
        <h2>How It Works</h2>
        <div className="steps">
          <div className="step">
            <div className="step-number">1</div>
            <h3>Upload</h3>
            <p>Upload your video files directly to our platform.</p>
          </div>
          <div className="step">
            <div className="step-number">2</div>
            <h3>Process</h3>
            <p>Our AI extracts audio and generates transcripts and summaries.</p>
          </div>
          <div className="step">
            <div className="step-number">3</div>
            <h3>Publish</h3>
            <p>Share your newly created podcasts and articles with the world.</p>
          </div>
        </div>
      </section>

      <section id="pricing" className="section-container pricing">
        <h2>Pricing</h2>
        <div className="grid">
          <div className="card">
            <h3>Starter</h3>
            <p>Free</p>
            <ul>
              <li>Unlimited Uploads</li>
              <li>Advanced AI processing</li>
              <li>Priority Support</li>
            </ul>
          </div>
        </div>
      </section>

      <section id="faq" className="section-container faq">
        <h2>FAQ</h2>
        <div className="faq-list">
          <div className="faq-item">
            <h3>What file formats are supported?</h3>
            <p>We support MP4, MOV, and AVI for video uploads.</p>
          </div>
          <div className="faq-item">
            <h3>How long does processing take?</h3>
            <p>Most videos are processed within 5-10 minutes depending on length.</p>
          </div>
        </div>
      </section>

      <Footer />
    </>
  );
}